# Generated by Django 4.2.3 on 2023-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
